Feature | BSSH V2 | Adding appsessions support | CROMSO-261
emedgene/fs_basespace pull request #42
Opened 2024-10-28 13:04 UTC by Shani-Daniel

[CROMSO-261](https://jira.illumina.com/browse/CROMSO-261)

2024-10-28 13:12 UTC, a-lahat approved these changes

2024-10-28 15:30 UTC, a-lahat submitted a review, later dismissed

2024-10-29 10:21 UTC, yairfischer requested changes

2024-10-29 10:21 UTC, yairfischer commented on fs_basespace/basespace_context.py
> +from BaseSpacePy.model.V2DatasetCompactList import V2DatasetCompactList
remove - it is not used

2024-10-29 10:21 UTC, yairfischer commented on fs_basespace/basespace_context.py
> +        params = {'sortby': 'Name', 'offset': offset, 'limit': limit, 'output_projects': [self.raw_obj.Id]}
use the get_id method

2024-10-29 10:38 UTC, Shani-Daniel commented on fs_basespace/basespace_context.py
> +        params = {'sortby': 'Name', 'offset': offset, 'limit': limit, 'output_projects': [self.raw_obj.Id]}
The method get_id was added in EntityContext, while this object is an instance of CategoryContext

2024-10-29 10:47 UTC, yairfischer approved these changes

2024-10-29 10:50 UTC, yairfischer commented on fs_basespace/basespace_context.py
> +        params = {'sortby': 'Name', 'offset': offset, 'limit': limit, 'output_projects': [self.raw_obj.Id]}
ok. correct

2024-10-29 10:50 UTC, a-lahat approved these changes

2024-10-29 12:48 UTC, merged